### ISSUE TITLE
Install problem "Invalid config field backend model"

### ISSUE THREAD

**Issue by elsondinardo** [jreinke/magento-elasticsearch#31]
After upload all magento files and cleaned cache i get this error trying access system/configuration/catalog/

Invalid config field backend model: bubble_search/adminhtml_system_config_backend_engine

Trace:
#0 /home/vuduloja/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(328): Mage::throwException('Invalid config ...')
#1 /home/vuduloja/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#2 /home/vuduloja/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#3 /home/vuduloja/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#4 /home/vuduloja/public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#5 /home/vuduloja/public_html/includes/src/__default.php(14252): Mage_Adminhtml_System_ConfigController->editAction()
#6 /home/vuduloja/public_html/includes/src/__default.php(18698): Mage_Core_Controller_Varien_Action->dispatch('edit')
#7 /home/vuduloja/public_html/includes/src/__default.php(18228): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/vuduloja/public_html/includes/src/__default.php(21056): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/vuduloja/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /home/vuduloja/public_html/index.php(83): Mage::run('', 'store')
#11 {main}

**Comment by elsondinardo** [comment]
Solved. Disabled compiler and install ok.
